language: rust
rust:
  - stable
  - nightly
os:
  - osx
  - linux
  - windows

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

notifications:
  email:
    on_success: never

before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy
